""" Common class for the constants related to database  """

DB_CONNECTION_URL = "postgres://postgres:postgres@localhost:5432/communitu-db"

""" Table names """
EVENT_DB_TABLE_NAME = "event"
USER_DB_TABLE_NAME = "_user"
CLUB_DB_TABLE_NAME = "club"
COMMENT_DB_TABLE_NAME = "comment"

""" Initial statements  """
# TODO CREATE TABLES ABOUT : NOTIFICATIONS, FOLLOWERS, USER AUTHORITIES, EVENT PARTICIPATION QUESTIONS

EVENT_DB_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS EVENT (
            ID SERIAL PRIMARY KEY,
            TITLE VARCHAR(60),
            EXPLANATION TEXT,
            START_DATE TIMESTAMP,
            END_DATE TIMESTAMP,
            QUOTA INTEGER,
            CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT TIMESTAMP WITH TIME ZONE
            )"""

USER_DB_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS _USER (
            ID SERIAL PRIMARY KEY,
            EMAIL VARCHAR(254) UNIQUE,
            PASSWORD VARCHAR (60),
            NAME VARCHAR (60),
            SURNAME VARCHAR (60),
            CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            )"""

CLUB_DB_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS CLUB (
            ID SERIAL PRIMARY KEY,
            NAME VARCHAR(80) UNIQUE,
            DESCRIPTION TEXT,
            CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            )"""

LINKER_CLUB_EVENT_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS LINKER_CLUB_EVENT (
            CLUB_ID INTEGER REFERENCES club(id) ON DELETE CASCADE,
            EVENT_ID INTEGER REFERENCES event(id) ON DELETE CASCADE 
            )"""

LINKER_CLUB_USER_EXECUTIVE_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS LINKER_CLUB_USER_EXECUTIVE (
            CLUB_ID INTEGER REFERENCES club(id) ON DELETE CASCADE,
            USER_ID INTEGER REFERENCES _user(id) ON DELETE CASCADE 
            )"""

LINKER_CLUB_USER_PARTICIPANT_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS LINKER_CLUB_USER_PARTICIPANT(
            CLUB_ID INTEGER REFERENCES club(id) ON DELETE CASCADE,
            USER_ID INTEGER REFERENCES _user(id) ON DELETE CASCADE 
            )"""

COMMENT_DB_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS COMMENT (
            ID SERIAL PRIMARY KEY,
            CONTENT TEXT,
            USER_ID INTEGER REFERENCES _user(id) ON DELETE CASCADE,
            EVENT_ID INTEGER REFERENCES event(id) ON DELETE CASCADE,
            CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT TIMESTAMP WITH TIME ZONE
            )"""

LINKER_COMMENT_REPLY_TABLE_INIT_STAT = """CREATE TABLE IF NOT EXISTS LINKER_COMMENT_REPLY (
            COMMENT_ID INTEGER REFERENCES comment(id) ON DELETE CASCADE,
            REPLY_TO INTEGER REFERENCES comment(id) ON DELETE CASCADE 
            )"""
